version: "3.1"
services:
  my-wpdb:
    image: mariadb
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMeIfYouWant
  my-wp:
    image: wordpress
    volumes:
      - ./src/:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini 
    ports:
      - "8080:80"
    links:
      - my-wpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: ChangeMeIfYouWant
  my-adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"